apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1m
  install:
    createNamespace: false
  chart:
    spec:
      chart: ingress-nginx
      version: '4.8.*'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
  values:
    controller:
      service:
        loadBalancerIP: 51.104.166.118
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: true
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz 
          service.beta.kubernetes.io/azure-dns-label-name: cloudtown 