apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: opentelemetry-operator-system
spec:
  interval: 1m
  chart:
    spec:
      chart: opentelemetry-operator
      version: '0.x.x'
      sourceRef:
        kind: HelmRepository
        name: opentelemetry-helm-charts
        namespace: opentelemetry-operator-system
