apiVersion: v1
kind: ConfigMap
metadata:
  name: service2-config
  namespace: distributed-tracing-azure-monitor
data:
  OpenTelemetry__OtlpExporter__Endpoint: "http://application-insights-collector:4317/"
  OpenTelemetry__OtlpExporter__ExportProcessorType: "Batch"
  OpenTelemetry__OtlpExporter__Protocol: "grpc"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  namespace: distributed-tracing-azure-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: "true"
        instrumentation.opentelemetry.io/otel-dotnet-auto-runtime: "linux-x64" 
        instrumentation.opentelemetry.io/inject-sdk: "true"
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: cloudtown.azurecr.io/opentelemetry/service2:cgd
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef: 
            name: service2-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: service2
  namespace: distributed-tracing-azure-monitor
spec:
  selector:
    app: service2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80