apiVersion: v1
kind: ConfigMap
metadata:
  name: service1-config
  namespace: distributed-tracing-azure-monitor
data:
  MicroservicesUrl__CustomerUrl: "http://service2:80"
  MicroservicesUrl__OrderUrl: "http://service3:80"
  OpenTelemetry__OtlpExporter__Endpoint: "http://application-insights-collector:4317/"
  OpenTelemetry__OtlpExporter__ExportProcessorType: "Batch"
  OpenTelemetry__OtlpExporter__Protocol: "grpc"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  namespace: distributed-tracing-azure-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: "true"
        instrumentation.opentelemetry.io/otel-dotnet-auto-runtime: "linux-x64" 
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: cloudtown.azurecr.io/opentelemetry/service1:cga
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef: 
            name: service1-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: distributed-tracing-azure-monitor
spec:
  selector:
    app: service1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80