apiVersion: v1
kind: ConfigMap
metadata:
  name: service3-config
  namespace: distributed-tracing-azure-monitor
data:
  OpenTelemetry__OtlpExporter__Endpoint: "http://application-insights-collector.distributed-tracing-azure-monitor.svc:4318/"
  OpenTelemetry__OtlpExporter__Protocol: "http"
  OpenTelemetry__OtlpExporter__ExportProcessorType: "Batch"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
  namespace: distributed-tracing-azure-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service3
  template:
    metadata:
      # annotations:
      #   instrumentation.opentelemetry.io/inject-dotnet: "true"
      #   instrumentation.opentelemetry.io/otel-dotnet-auto-runtime: "linux-x64" 
      #   instrumentation.opentelemetry.io/inject-sdk: "true"
      labels:
        app: service3
    spec:
      containers:
      - name: service3
        image: cloudtown.azurecr.io/opentelemetry/service3:cgb
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef: 
            name: service3-config
        - secretRef:
            name: service3-secret
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: service3
  namespace: distributed-tracing-azure-monitor
spec:
  selector:
    app: service3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80