apiVersion: v1
kind: ConfigMap
metadata:
  name: service1-config
  namespace: distributed-tracing-azure-monitor
data:
  MicroservicesUrl__CustomerUrl: "http://service2:80"
  MicroservicesUrl__OrderUrl: "http://service3:80"
  OpenTelemetry__OtlpExporter__Endpoint: "http://application-insights-collector.distributed-tracing-azure-monitor.svc:4318/"
  OpenTelemetry__OtlpExporter__Protocol: "http"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  namespace: distributed-tracing-azure-monitor
  annotations:
    instrumentation.opentelemetry.io/inject-dotnet: "true"
    instrumentation.opentelemetry.io/otel-dotnet-auto-runtime: "linux-x64" 
    instrumentation.opentelemetry.io/inject-sdk: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: "true"
        instrumentation.opentelemetry.io/otel-dotnet-auto-runtime: "linux-x64" 
        instrumentation.opentelemetry.io/inject-sdk: "true"
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: cloudtown.azurecr.io/opentelemetry/service1:cgc
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef: 
            name: service1-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: distributed-tracing-azure-monitor
spec:
  selector:
    app: service1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service1
  namespace: distributed-tracing-azure-monitor
  annotations:
    nginx.ingress.kubernetes.io/enable-opentelemetry: "true"
    nginx.ingress.kubernetes.io/otlp-collector-host: application-insights-collector
    nginx.ingress.kubernetes.io/opentelemetry-trust-incoming-span: "true"
  labels:
    app: service1
spec:
  ingressClassName: nginx
  rules:
  - host: cloudtown.northeurope.cloudapp.azure.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: service1
            port: 
              number: 80
