apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: application-insights
  namespace: distributed-tracing-azure-monitor
spec:
  replicas: 3
  observability: 
    metrics:
      enableMetrics: true
  env:
    - name: INSTRUMENTATIONKEY
      valueFrom: 
        secretKeyRef:
          name: telemetry
          key: InstrumentationKey

  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      otlp/2:
        protocols:
          grpc:
            endpoint: 0.0.0.0:55690

    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s
      batch/test:

    exporters:
      azuremonitor:
        endpoint: https://dc.services.visualstudio.com/v2/track
        instrumentation_key: ${env:INSTRUMENTATIONKEY}
      logging:

    extensions:
      health_check:
      pprof:
      zpages:

    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [azuremonitor, logging]
        traces/2:
          receivers: [otlp/2]
          processors: [batch/test]
          exporters: [azuremonitor, logging]

        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [azuremonitor, logging]